# Multi Layer Perceptron

XOR 문제를 Multi-layer perceptron으로 해결해보자!

## Simple MLP

In [1]:
import torch
from torch import nn, optim

device = 'cuda' if torch.cuda.is_available() else 'cpu'

torch.manual_seed(777)
if device == 'cuda':
    torch.cuda.manual_seed_all(777)

In [2]:
X = torch.FloatTensor([[0, 0], [0, 1], [1, 0], [1, 1]]).to(device)
Y = torch.FloatTensor([[0], [1], [1], [0]]).to(device)

In [3]:
class SimpleMLP(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear1 = nn.Linear(2, 2, bias=True)
        self.linear2 = nn.Linear(2, 1, bias=True)
        self.sigmoid = nn.Sigmoid()
        
    def forward(self, x):
        x = self.linear1(x)
        x = self.sigmoid(x)
        x = self.linear2(x)
        x = self.sigmoid(x)
        return x
    
    
model = SimpleMLP().to(device)

In [4]:
criterion = nn.BCELoss().to(device)
optimizer = optim.SGD(model.parameters(), lr=1)

In [5]:
n_epochs = 10000

for epoch in range(1, n_epochs+1):
    optimizer.zero_grad()
    h = model(X)
    
    loss = criterion(h, Y)
    loss.backward()
    optimizer.step()
    
    if epoch % 100 == 0:
        print("Epoch {:5d}/{} Loss: {:.6f}".format(
            epoch, n_epochs, loss))

Epoch   100/10000 Loss: 0.693165
Epoch   200/10000 Loss: 0.693158
Epoch   300/10000 Loss: 0.693152
Epoch   400/10000 Loss: 0.693146
Epoch   500/10000 Loss: 0.693141
Epoch   600/10000 Loss: 0.693136
Epoch   700/10000 Loss: 0.693130
Epoch   800/10000 Loss: 0.693122
Epoch   900/10000 Loss: 0.693113
Epoch  1000/10000 Loss: 0.693100
Epoch  1100/10000 Loss: 0.693082
Epoch  1200/10000 Loss: 0.693057
Epoch  1300/10000 Loss: 0.693020
Epoch  1400/10000 Loss: 0.692961
Epoch  1500/10000 Loss: 0.692867
Epoch  1600/10000 Loss: 0.692705
Epoch  1700/10000 Loss: 0.692400
Epoch  1800/10000 Loss: 0.691740
Epoch  1900/10000 Loss: 0.689995
Epoch  2000/10000 Loss: 0.683946
Epoch  2100/10000 Loss: 0.656723
Epoch  2200/10000 Loss: 0.435805
Epoch  2300/10000 Loss: 0.136151
Epoch  2400/10000 Loss: 0.066670
Epoch  2500/10000 Loss: 0.042328
Epoch  2600/10000 Loss: 0.030540
Epoch  2700/10000 Loss: 0.023720
Epoch  2800/10000 Loss: 0.019314
Epoch  2900/10000 Loss: 0.016250
Epoch  3000/10000 Loss: 0.014003
Epoch  310

In [6]:
with torch.no_grad():
    hypothesis = model(X)
    predicted = (hypothesis > 0.5).float()
    accuracy = (predicted == Y).float().mean()
    
    print("Predicted\n", predicted.detach().cpu().numpy())
    print("Answer\n", Y.detach().cpu().numpy())
    print("Accuracy: ", accuracy.detach().cpu().numpy())

Predicted
 [[0.]
 [1.]
 [1.]
 [0.]]
Answer
 [[0.]
 [1.]
 [1.]
 [0.]]
Accuracy:  1.0


## Wide & Deep MLP

In [7]:
class WideAndDeepMLP(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear1 = nn.Linear(2, 10, bias=True)
        self.linear2 = nn.Linear(10, 10, bias=True)
        self.linear3 = nn.Linear(10, 10, bias=True)
        self.linear4 = nn.Linear(10, 1, bias=True)
        self.sigmoid = nn.Sigmoid()
        
    def forward(self, x):
        x = self.sigmoid(self.linear1(x))
        x = self.sigmoid(self.linear2(x))
        x = self.sigmoid(self.linear3(x))
        x = self.sigmoid(self.linear4(x))
        return x
    
    
model = WideAndDeepMLP().to(device)

In [8]:
criterion = nn.BCELoss().to(device)
optimizer = optim.SGD(model.parameters(), lr=1)

In [9]:
for epoch in range(1, n_epochs+1):
    optimizer.zero_grad()
    h = model(X)
    
    loss = criterion(h, Y)
    loss.backward()
    optimizer.step()
    
    if epoch % 100 == 0:
        print("Epoch {:5d}/{} Loss: {:.6f}".format(
            epoch, n_epochs, loss))

Epoch   100/10000 Loss: 0.693111
Epoch   200/10000 Loss: 0.693102
Epoch   300/10000 Loss: 0.693092
Epoch   400/10000 Loss: 0.693081
Epoch   500/10000 Loss: 0.693068
Epoch   600/10000 Loss: 0.693052
Epoch   700/10000 Loss: 0.693033
Epoch   800/10000 Loss: 0.693010
Epoch   900/10000 Loss: 0.692981
Epoch  1000/10000 Loss: 0.692944
Epoch  1100/10000 Loss: 0.692896
Epoch  1200/10000 Loss: 0.692832
Epoch  1300/10000 Loss: 0.692743
Epoch  1400/10000 Loss: 0.692614
Epoch  1500/10000 Loss: 0.692418
Epoch  1600/10000 Loss: 0.692102
Epoch  1700/10000 Loss: 0.691546
Epoch  1800/10000 Loss: 0.690449
Epoch  1900/10000 Loss: 0.687879
Epoch  2000/10000 Loss: 0.679860
Epoch  2100/10000 Loss: 0.641612
Epoch  2200/10000 Loss: 0.549555
Epoch  2300/10000 Loss: 0.508556
Epoch  2400/10000 Loss: 0.487795
Epoch  2500/10000 Loss: 0.390165
Epoch  2600/10000 Loss: 0.020705
Epoch  2700/10000 Loss: 0.007833
Epoch  2800/10000 Loss: 0.004558
Epoch  2900/10000 Loss: 0.003135
Epoch  3000/10000 Loss: 0.002357
Epoch  310

In [10]:
with torch.no_grad():
    hypothesis = model(X)
    predicted = (hypothesis > 0.5).float()
    accuracy = (predicted == Y).float().mean()
    
    print("Predicted\n", predicted.detach().cpu().numpy())
    print("Answer\n", Y.detach().cpu().numpy())
    print("Accuracy: ", accuracy.detach().cpu().numpy())

Predicted
 [[0.]
 [1.]
 [1.]
 [0.]]
Answer
 [[0.]
 [1.]
 [1.]
 [0.]]
Accuracy:  1.0
