# Logistic Regression

Logistic Regression을 구현해보자!

## Dataset

In [1]:
import torch

x_data = [[1, 2], [2, 3], [3, 1], [4, 3], [5, 3], [6, 2]]
y_data = [[0], [0], [0], [1], [1], [1]]

x_train = torch.FloatTensor(x_data)
y_train = torch.FloatTensor(y_data)

print(x_train.shape, y_train.shape)

torch.Size([6, 2]) torch.Size([6, 1])


## Sigmoid

In [2]:
W = torch.zeros((2, 1), requires_grad=True)
b = torch.zeros(1, requires_grad=True)

In [3]:
hypothesis = 1 / (1+torch.exp(-(x_train.matmul(W) + b)))
print(hypothesis)
print(hypothesis.shape)

hypothesis = torch.sigmoid(x_train.matmul(W) + b)
print(hypothesis)
print(hypothesis.shape)

tensor([[0.5000],
        [0.5000],
        [0.5000],
        [0.5000],
        [0.5000],
        [0.5000]], grad_fn=<MulBackward0>)
torch.Size([6, 1])
tensor([[0.5000],
        [0.5000],
        [0.5000],
        [0.5000],
        [0.5000],
        [0.5000]], grad_fn=<SigmoidBackward>)
torch.Size([6, 1])


## Loss

In [4]:
import torch.nn.functional as F

loss = -((y_train * torch.log(hypothesis)) + ((1-y_train) * torch.log(hypothesis)))
loss = loss.mean()
print(loss)

loss = F.binary_cross_entropy(hypothesis, y_train)
print(loss)

tensor(0.6931, grad_fn=<MeanBackward0>)
tensor(0.6931, grad_fn=<BinaryCrossEntropyBackward>)


## Training Procedure

In [5]:
from torch import optim

optimizer = optim.SGD([W, b], lr=0.1)
n_epochs = 1000

for epoch in range(1, n_epochs+1):
    optimizer.zero_grad()
    hypothesis = torch.sigmoid(x_train.matmul(W) + b)
    
    loss = F.binary_cross_entropy(hypothesis, y_train)
    loss.backward()
    optimizer.step()
    
    print("Epoch {:4d}/{}, Loss: {:.6f}".format(epoch, n_epochs, loss))

Epoch    1/1000, Loss: 0.693147
Epoch    2/1000, Loss: 0.647504
Epoch    3/1000, Loss: 0.631011
Epoch    4/1000, Loss: 0.621414
Epoch    5/1000, Loss: 0.613788
Epoch    6/1000, Loss: 0.606917
Epoch    7/1000, Loss: 0.600467
Epoch    8/1000, Loss: 0.594335
Epoch    9/1000, Loss: 0.588479
Epoch   10/1000, Loss: 0.582878
Epoch   11/1000, Loss: 0.577517
Epoch   12/1000, Loss: 0.572382
Epoch   13/1000, Loss: 0.567461
Epoch   14/1000, Loss: 0.562743
Epoch   15/1000, Loss: 0.558217
Epoch   16/1000, Loss: 0.553873
Epoch   17/1000, Loss: 0.549700
Epoch   18/1000, Loss: 0.545691
Epoch   19/1000, Loss: 0.541835
Epoch   20/1000, Loss: 0.538126
Epoch   21/1000, Loss: 0.534555
Epoch   22/1000, Loss: 0.531115
Epoch   23/1000, Loss: 0.527800
Epoch   24/1000, Loss: 0.524602
Epoch   25/1000, Loss: 0.521517
Epoch   26/1000, Loss: 0.518537
Epoch   27/1000, Loss: 0.515658
Epoch   28/1000, Loss: 0.512875
Epoch   29/1000, Loss: 0.510182
Epoch   30/1000, Loss: 0.507576
Epoch   31/1000, Loss: 0.505051
Epoch   

Epoch  493/1000, Loss: 0.235684
Epoch  494/1000, Loss: 0.235411
Epoch  495/1000, Loss: 0.235139
Epoch  496/1000, Loss: 0.234867
Epoch  497/1000, Loss: 0.234596
Epoch  498/1000, Loss: 0.234326
Epoch  499/1000, Loss: 0.234056
Epoch  500/1000, Loss: 0.233787
Epoch  501/1000, Loss: 0.233518
Epoch  502/1000, Loss: 0.233250
Epoch  503/1000, Loss: 0.232983
Epoch  504/1000, Loss: 0.232716
Epoch  505/1000, Loss: 0.232449
Epoch  506/1000, Loss: 0.232184
Epoch  507/1000, Loss: 0.231918
Epoch  508/1000, Loss: 0.231654
Epoch  509/1000, Loss: 0.231390
Epoch  510/1000, Loss: 0.231126
Epoch  511/1000, Loss: 0.230863
Epoch  512/1000, Loss: 0.230601
Epoch  513/1000, Loss: 0.230339
Epoch  514/1000, Loss: 0.230078
Epoch  515/1000, Loss: 0.229817
Epoch  516/1000, Loss: 0.229557
Epoch  517/1000, Loss: 0.229297
Epoch  518/1000, Loss: 0.229038
Epoch  519/1000, Loss: 0.228780
Epoch  520/1000, Loss: 0.228522
Epoch  521/1000, Loss: 0.228265
Epoch  522/1000, Loss: 0.228008
Epoch  523/1000, Loss: 0.227751
Epoch  5

## Evaluation

In [6]:
probas = torch.sigmoid(x_train.matmul(W) + b)
prediction = (probas >= torch.FloatTensor([0.5])).float()

print(probas)
print(prediction)
print(y_train)

tensor([[0.0299],
        [0.1576],
        [0.3006],
        [0.7833],
        [0.9408],
        [0.9806]], grad_fn=<SigmoidBackward>)
tensor([[0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.]])
tensor([[0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.]])


# Higher Implementation with Class

In [7]:
from torch import nn

class LogisticRegression(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(2, 1)
        self.sigmoid = nn.Sigmoid()
        
    def forward(self, x):
        return self.sigmoid(self.linear(x))
    
model = LogisticRegression()

In [8]:
optimizer = optim.SGD(model.parameters(), lr=0.1)
n_epochs = 1000

for epoch in range(1, n_epochs+1):
    h = model(x_train)
    optimizer.zero_grad()
    
    loss = F.binary_cross_entropy(h, y_train)
    loss.backward()
    optimizer.step()
    
    predictions = (h >= torch.FloatTensor([0.5])).float()
    accuracy = torch.sum(predictions == y_train).item()/len(y_train)

    print("Epoch {:3d}/{}, Loss: {:.6f}, Accuracy: {:.2f}%".format(
        epoch, n_epochs, loss, accuracy))

Epoch   1/1000, Loss: 0.889206, Accuracy: 0.50%
Epoch   2/1000, Loss: 0.739166, Accuracy: 0.17%
Epoch   3/1000, Loss: 0.696270, Accuracy: 0.50%
Epoch   4/1000, Loss: 0.680186, Accuracy: 0.50%
Epoch   5/1000, Loss: 0.670484, Accuracy: 0.50%
Epoch   6/1000, Loss: 0.662618, Accuracy: 0.50%
Epoch   7/1000, Loss: 0.655471, Accuracy: 0.50%
Epoch   8/1000, Loss: 0.648738, Accuracy: 0.50%
Epoch   9/1000, Loss: 0.642325, Accuracy: 0.50%
Epoch  10/1000, Loss: 0.636194, Accuracy: 0.50%
Epoch  11/1000, Loss: 0.630324, Accuracy: 0.50%
Epoch  12/1000, Loss: 0.624700, Accuracy: 0.50%
Epoch  13/1000, Loss: 0.619309, Accuracy: 0.50%
Epoch  14/1000, Loss: 0.614139, Accuracy: 0.50%
Epoch  15/1000, Loss: 0.609177, Accuracy: 0.50%
Epoch  16/1000, Loss: 0.604413, Accuracy: 0.83%
Epoch  17/1000, Loss: 0.599837, Accuracy: 0.83%
Epoch  18/1000, Loss: 0.595438, Accuracy: 0.83%
Epoch  19/1000, Loss: 0.591207, Accuracy: 0.83%
Epoch  20/1000, Loss: 0.587136, Accuracy: 0.83%
Epoch  21/1000, Loss: 0.583216, Accuracy

Epoch 257/1000, Loss: 0.345337, Accuracy: 0.83%
Epoch 258/1000, Loss: 0.344805, Accuracy: 0.83%
Epoch 259/1000, Loss: 0.344273, Accuracy: 0.83%
Epoch 260/1000, Loss: 0.343743, Accuracy: 0.83%
Epoch 261/1000, Loss: 0.343214, Accuracy: 0.83%
Epoch 262/1000, Loss: 0.342686, Accuracy: 0.83%
Epoch 263/1000, Loss: 0.342160, Accuracy: 0.83%
Epoch 264/1000, Loss: 0.341635, Accuracy: 0.83%
Epoch 265/1000, Loss: 0.341112, Accuracy: 0.83%
Epoch 266/1000, Loss: 0.340589, Accuracy: 0.83%
Epoch 267/1000, Loss: 0.340069, Accuracy: 0.83%
Epoch 268/1000, Loss: 0.339549, Accuracy: 0.83%
Epoch 269/1000, Loss: 0.339031, Accuracy: 0.83%
Epoch 270/1000, Loss: 0.338514, Accuracy: 0.83%
Epoch 271/1000, Loss: 0.337998, Accuracy: 0.83%
Epoch 272/1000, Loss: 0.337483, Accuracy: 0.83%
Epoch 273/1000, Loss: 0.336970, Accuracy: 0.83%
Epoch 274/1000, Loss: 0.336458, Accuracy: 0.83%
Epoch 275/1000, Loss: 0.335948, Accuracy: 0.83%
Epoch 276/1000, Loss: 0.335438, Accuracy: 0.83%
Epoch 277/1000, Loss: 0.334930, Accuracy

Epoch 516/1000, Loss: 0.242807, Accuracy: 1.00%
Epoch 517/1000, Loss: 0.242518, Accuracy: 1.00%
Epoch 518/1000, Loss: 0.242231, Accuracy: 1.00%
Epoch 519/1000, Loss: 0.241944, Accuracy: 1.00%
Epoch 520/1000, Loss: 0.241657, Accuracy: 1.00%
Epoch 521/1000, Loss: 0.241372, Accuracy: 1.00%
Epoch 522/1000, Loss: 0.241087, Accuracy: 1.00%
Epoch 523/1000, Loss: 0.240802, Accuracy: 1.00%
Epoch 524/1000, Loss: 0.240518, Accuracy: 1.00%
Epoch 525/1000, Loss: 0.240235, Accuracy: 1.00%
Epoch 526/1000, Loss: 0.239953, Accuracy: 1.00%
Epoch 527/1000, Loss: 0.239671, Accuracy: 1.00%
Epoch 528/1000, Loss: 0.239389, Accuracy: 1.00%
Epoch 529/1000, Loss: 0.239108, Accuracy: 1.00%
Epoch 530/1000, Loss: 0.238828, Accuracy: 1.00%
Epoch 531/1000, Loss: 0.238549, Accuracy: 1.00%
Epoch 532/1000, Loss: 0.238270, Accuracy: 1.00%
Epoch 533/1000, Loss: 0.237992, Accuracy: 1.00%
Epoch 534/1000, Loss: 0.237714, Accuracy: 1.00%
Epoch 535/1000, Loss: 0.237437, Accuracy: 1.00%
Epoch 536/1000, Loss: 0.237160, Accuracy

Epoch 690/1000, Loss: 0.200799, Accuracy: 1.00%
Epoch 691/1000, Loss: 0.200598, Accuracy: 1.00%
Epoch 692/1000, Loss: 0.200397, Accuracy: 1.00%
Epoch 693/1000, Loss: 0.200196, Accuracy: 1.00%
Epoch 694/1000, Loss: 0.199996, Accuracy: 1.00%
Epoch 695/1000, Loss: 0.199797, Accuracy: 1.00%
Epoch 696/1000, Loss: 0.199598, Accuracy: 1.00%
Epoch 697/1000, Loss: 0.199399, Accuracy: 1.00%
Epoch 698/1000, Loss: 0.199200, Accuracy: 1.00%
Epoch 699/1000, Loss: 0.199002, Accuracy: 1.00%
Epoch 700/1000, Loss: 0.198805, Accuracy: 1.00%
Epoch 701/1000, Loss: 0.198607, Accuracy: 1.00%
Epoch 702/1000, Loss: 0.198410, Accuracy: 1.00%
Epoch 703/1000, Loss: 0.198214, Accuracy: 1.00%
Epoch 704/1000, Loss: 0.198018, Accuracy: 1.00%
Epoch 705/1000, Loss: 0.197822, Accuracy: 1.00%
Epoch 706/1000, Loss: 0.197626, Accuracy: 1.00%
Epoch 707/1000, Loss: 0.197431, Accuracy: 1.00%
Epoch 708/1000, Loss: 0.197237, Accuracy: 1.00%
Epoch 709/1000, Loss: 0.197042, Accuracy: 1.00%
Epoch 710/1000, Loss: 0.196848, Accuracy